### ISSUE TITLE
6 buttons piFBA games always have DisplaySmoothStretch=1

### ISSUE THREAD

**Issue by nekomania** [digitalLumberjack/recalbox-emulationstation#10]
In System Settings there is a setting called "Smooth Games", I prefer to turn it OFF.
It works fine in RetroArch and FBA's 2 buttons games.
I believe it might be a bug somewhere in the fba2x6bth.cfg file.

Thanks ;-)

**Comment by digitalLumberjack** [comment]
Thanks I'll check it

Le jeu. 12 févr. 2015 à 18:08, nekomania <notifications@github.com> a
écrit :

**Comment by digitalLumberjack** [comment]
corrected with commit  4a8ae9c14dbff43d3660487a3520e055c486a287
