### ISSUE TITLE
Crashes while scraping images

### ISSUE THREAD

**Issue by jayminer81** [digitalLumberjack/recalbox-emulationstation#6]
Emulationstation runs out of memory and crashes after scraping for about 20 minutes, seems to depend on the images though how long it takes, but if you start scraping and have a terminal open and run free every once in a while you will see how the memory is slowly being eaten up until it finally crashes.

**Comment by digitalLumberjack** [comment]
i report that on https://github.com/Aloshi/EmulationStation/issues and i will take a look
Thanks

**Comment by digitalLumberjack** [comment]
The bug has been corrected in emulationstation, i'll pull the master branch and add the correction in the next release !
